"""update models

Revision ID: c752892fccdc
Revises: a68e25fa042a
Create Date: 2024-08-26 22:01:00.433083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c752892fccdc'
down_revision: Union[str, None] = 'a68e25fa042a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('NAZORATCHI', 'AFISSANT', 'USER', 'HODIM', name='role'),
               type_=sa.Enum('nazoratchi', 'afissant', 'hodim', 'user', name='role_enum_type'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('nazoratchi', 'afissant', 'hodim', 'user', name='role_enum_type'),
               type_=postgresql.ENUM('NAZORATCHI', 'AFISSANT', 'USER', 'HODIM', name='role'),
               nullable=True)
    # ### end Alembic commands ###
